import React from 'react';
import { Box, Typography } from '@mui/material';
import { Sparkles, Lock } from 'lucide-react';
import { motion } from 'framer-motion';

const SynthesisTrigger = ({ onClick, ready }) => {
  return (
    <motion.div 
        initial={{ opacity: 0, y: 20 }} 
        animate={{ opacity: 1, y: 0 }}
        whileHover={{ scale: ready ? 1.02 : 1 }}
    >
        <Box 
            onClick={ready ? onClick : null}
            sx={{ 
                bgcolor: 'background.paper', borderRadius: 4, p: 4, 
                border: '2px dashed', borderColor: ready ? '#10b981' : 'divider',
                cursor: ready ? 'pointer' : 'default',
                position: 'relative', overflow: 'hidden',
                textAlign: 'center', transition: 'all 0.3s ease',
                bgcolor: ready ? 'rgba(16, 185, 129, 0.02)' : 'background.paper'
            }}
        >
            {ready && (
                <Box sx={{ 
                    position: 'absolute', top: 20, right: -30, bgcolor: '#10b981', color: 'white', 
                    px: 4, py: 0.5, transform: 'rotate(45deg)', fontWeight: 800, fontSize: 10, letterSpacing: 2
                }}>
                    COMPLETED
                </Box>
            )}

            <Box sx={{ 
                width: 64, height: 64, borderRadius: '24px', mx: 'auto', mb: 2,
                bgcolor: ready ? '#d1fae5' : '#f1f5f9', color: ready ? '#059669' : '#94a3b8',
                display: 'flex', alignItems: 'center', justifyContent: 'center'
            }}>
                {ready ? <Sparkles size={32} /> : <Lock size={32} />}
            </Box>

            <Typography variant="h6" fontWeight={700} color={ready ? 'text.primary' : 'text.secondary'}>
                {ready ? 'Consensus Reached' : 'Waiting for Synthesis...'}
            </Typography>
            
            <Typography variant="body2" color="text.secondary" sx={{ maxWidth: 300, mx: 'auto', mt: 1 }}>
                {ready ? 'Click to unseal the final strategic synthesis report generated by the swarm.' : 'The engine is currently processing divergence resolution.'}
            </Typography>
        </Box>
    </motion.div>
  );
};

export default SynthesisTrigger;